# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8f6ec52b22dc8c754f683a6b2756a688"
name = "lucrative-projection-app"
handle = "lucrative-projection-app-7"
application_url = "https://ways-provide-exhibition-validity.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-1f97fa38.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://ways-provide-exhibition-validity.trycloudflare.com/auth/callback",
  "https://ways-provide-exhibition-validity.trycloudflare.com/auth/shopify/callback",
  "https://ways-provide-exhibition-validity.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
